"""Auto-generated by ManaSplice from main.py."""

from __future__ import annotations
import asyncio
import json
import math
import os
import random
import statistics
import time
from dataclasses import dataclass
from functools import wraps
from pathlib import Path
from typing import Any, Callable, Iterable
from modules.expensive_simulation import expensive_simulation
from modules.save_report import save_report
from modules.load_users import load_users

def require_positive_numbers(values: Iterable[float]) -> None:
    if any(v < 0 for v in values):
        raise ValueError("negative values are not allowed")

def complicated_transform(values: list[float]) -> dict[str, Any]:
    require_positive_numbers(values)

    def zscore(v: float, mean_: float, std_: float) -> float:
        if std_ == 0:
            return 0.0
        return (v - mean_) / std_

    mean_val = statistics.mean(values)
    std_val = statistics.pstdev(values)

    transformed = [round(math.log(v + 1) * 3.7, 4) for v in values]
    zscores = [round(zscore(v, mean_val, std_val), 4) for v in values]

    return {
        "input": values,
        "transformed": transformed,
        "zscores": zscores,
        "max": max(values),
        "min": min(values),
    }
