"""Auto-generated by ManaSplice from main.py."""

from __future__ import annotations
import asyncio
import json
import math
import os
import random
import statistics
import time
from dataclasses import dataclass
from functools import wraps
from pathlib import Path
from typing import Any, Callable, Iterable

def require_positive_numbers(values: Iterable[float]) -> None:
    if any(v < 0 for v in values):
        raise ValueError("negative values are not allowed")

def expensive_simulation(seed: int, n: int = 5000) -> dict[str, float]:
    rng = random.Random(seed)
    samples = [rng.uniform(0, 1000) for _ in range(n)]

    require_positive_numbers(samples)

    total = sum(math.sqrt(x) for x in samples)
    avg = total / n
    peak = max(samples)

    return {
        "avg_root": round(avg, 4),
        "peak": round(peak, 4),
    }
