"""Auto-generated by pySplit from main.py."""

from __future__ import annotations
import asyncio
import json
import math
import os
import random
import statistics
import time
from dataclasses import dataclass
from functools import wraps
from pathlib import Path
from typing import Any, Callable, Iterable
from modules.expensive_simulation import expensive_simulation
from modules.save_report import save_report

CACHE: dict[str, Any] = {}

@dataclass
class User:
    id: int
    name: str
    scores: list[int]

def normalize_name(name: str) -> str:
    return " ".join(part.capitalize() for part in name.strip().split())

def load_users(path: str) -> list[User]:
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"missing file: {path}")

    raw = json.loads(file_path.read_text(encoding="utf-8"))
    users = [
        User(
            id=item["id"],
            name=normalize_name(item["name"]),
            scores=item.get("scores", []),
        )
        for item in raw
    ]
    CACHE["users"] = users
    return users
