"""Auto-generated by pySplit from main.py."""

from __future__ import annotations
import asyncio
import json
import math
import os
import random
import statistics
import time
from dataclasses import dataclass
from functools import wraps
from pathlib import Path
from typing import Any, Callable, Iterable
from modules.expensive_simulation import expensive_simulation

APP_NAME = "MegaTestApp"

DATA_DIR = Path("data")

def save_report(stats: dict[str, dict[str, float]], out_path: str) -> str:
    DATA_DIR.mkdir(exist_ok=True)

    payload = {
        "app": APP_NAME,
        "generated_at": time.time(),
        "stats": stats,
    }

    path = Path(out_path)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return str(path.resolve())
