from __future__ import annotations

import ast
import difflib
from pathlib import Path

from .analysis import statement_start_lineno
from .exceptions import FunctionExtractionError
from .models import FileChange


def extract_lines(source_text: str, start_lineno: int, end_lineno: int) -> str:
    lines = source_text.splitlines(keepends=True)
    return "".join(lines[start_lineno - 1 : end_lineno])


def build_import_block(
    imports: list[ast.stmt],
    source_text: str,
    package_mode: bool,
    output_package: str,
    required_import_names: set[str],
) -> str:
    lines = source_text.splitlines(keepends=True)
    blocks: list[str] = []

    for stmt in imports:
        if isinstance(stmt, ast.ImportFrom) and stmt.module == "__future__":
            blocks.append("".join(lines[stmt.lineno - 1 : stmt.end_lineno]).rstrip())
            continue

        filtered = _filter_import(stmt, source_text, required_import_names)
        if filtered is None:
            continue
        if isinstance(stmt, ast.ImportFrom) and stmt.module == output_package:
            blocks.extend(_rewrite_package_import(filtered, package_mode, output_package))
            continue
        blocks.append(filtered)

    if not blocks:
        return ""
    return "\n".join(blocks) + "\n\n"


def compose_new_module_text(
    source_path: Path,
    import_block: str,
    dependency_block: str,
    function_block: str,
) -> str:
    header = f'"""Auto-generated by Splinter from {source_path.name}."""\n\n'
    function_block = function_block.strip() + "\n"
    return header + import_block + dependency_block + function_block


def updated_package_exports(existing: str, function_name: str) -> str:
    export_line = f"from .{function_name} import {function_name}\n"
    lines = existing.splitlines(keepends=True)

    if export_line in lines:
        return existing

    lines.append(export_line)
    lines = sorted(set(lines), key=str.casefold)
    return "".join(lines)


def updated_package_exports_for_group(existing: str, group_module_name: str, function_names: list[str]) -> str:
    names_str = ", ".join(sorted(function_names))
    export_line = f"from .{group_module_name} import {names_str}\n"

    lines = existing.splitlines(keepends=True)
    filtered = [
        line for line in lines if not any(line.strip() == f"from .{name} import {name}" for name in function_names)
    ]
    if export_line in filtered:
        return "".join(filtered)

    filtered.append(export_line)
    filtered = sorted(set(filtered), key=str.casefold)
    return "".join(filtered)


def remove_function_block(source_text: str, start_lineno: int, end_lineno: int) -> str:
    return remove_function_blocks(source_text, [(start_lineno, end_lineno)])


def remove_function_blocks(source_text: str, ranges: list[tuple[int, int]]) -> str:
    lines = source_text.splitlines(keepends=True)
    for start, end in sorted(ranges, key=lambda item: item[0], reverse=True):
        del lines[start - 1 : end]

    updated = "".join(lines)
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated.lstrip("\n")


def compute_replacement_import(package_mode: bool, output_package: str, function_name: str) -> str:
    if package_mode:
        return f"from .{output_package} import {function_name}"
    return f"from {output_package} import {function_name}"


def compute_group_import_statement(package_mode: bool, output_package: str, function_names: list[str]) -> str:
    names_str = ", ".join(sorted(function_names))
    if package_mode:
        return f"from .{output_package} import {names_str}"
    return f"from {output_package} import {names_str}"


def insert_import(source_text: str, import_statement: str) -> str:
    lines = source_text.splitlines(keepends=True)
    tree = ast.parse(source_text) if source_text.strip() else ast.parse("")

    merged_source = _merge_with_existing_package_import(tree, lines, import_statement)
    if merged_source is not None:
        return merged_source

    insert_after = 0
    body = getattr(tree, "body", [])

    if (
        body
        and isinstance(body[0], ast.Expr)
        and isinstance(body[0].value, ast.Constant)
        and isinstance(body[0].value.value, str)
    ):
        insert_after = body[0].end_lineno or 0

    for stmt in body:
        if isinstance(stmt, (ast.Import, ast.ImportFrom)):
            insert_after = max(insert_after, stmt.end_lineno or 0)

    new_line = import_statement + "\n"

    if insert_after == 0:
        return new_line + ("\n" if source_text.strip() else "") + source_text

    lines.insert(insert_after, new_line)
    updated = "".join(lines)
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated


def validate_output_package(output_package: str) -> None:
    parts = output_package.split(".")
    if not output_package or any(not part.isidentifier() for part in parts):
        raise FunctionExtractionError(
            f"Invalid output package '{output_package}'. "
            "Use a dotted Python package path like 'modules' or 'generated'."
        )


def validate_split_outputs(file_changes: list[FileChange]) -> None:
    for change in file_changes:
        if not change.after_text:
            continue
        try:
            ast.parse(change.after_text)
        except SyntaxError as exc:
            raise FunctionExtractionError(
                f"Validation failed for '{change.path.name}': {exc.msg} at line {exc.lineno}."
            ) from exc


def build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        before = change.before_text.splitlines()
        after = change.after_text.splitlines()
        diff_lines = list(
            difflib.unified_diff(
                before,
                after,
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs


def _filter_import(stmt: ast.stmt, source_text: str, required_import_names: set[str]) -> str | None:
    if not isinstance(stmt, (ast.Import, ast.ImportFrom)) or stmt.end_lineno is None:
        return None
    if isinstance(stmt, ast.ImportFrom) and any(alias.name == "*" for alias in stmt.names):
        return extract_lines(source_text, stmt.lineno, stmt.end_lineno).rstrip()

    kept = [alias for alias in stmt.names if _import_alias_bound_name(stmt, alias) in required_import_names]
    if not kept:
        return None

    if isinstance(stmt, ast.Import):
        names = ", ".join(_format_alias(alias) for alias in kept)
        return f"import {names}"

    module_path = "." * stmt.level + (stmt.module or "")
    names = ", ".join(_format_alias(alias) for alias in kept)
    return f"from {module_path} import {names}"


def _rewrite_package_import(import_text: str, package_mode: bool, output_package: str) -> list[str]:
    stmt = ast.parse(import_text).body[0]
    if not isinstance(stmt, ast.ImportFrom):
        return [import_text]

    rewritten: list[str] = []
    for alias in sorted(stmt.names, key=lambda item: item.name.casefold()):
        import_name = alias.name
        if alias.asname is None:
            if package_mode:
                rewritten.append(f"from .{import_name} import {import_name}")
            else:
                rewritten.append(f"from {output_package}.{import_name} import {import_name}")
            continue

        if package_mode:
            rewritten.append(f"from .{import_name} import {import_name} as {alias.asname}")
        else:
            rewritten.append(f"from {output_package}.{import_name} import {import_name} as {alias.asname}")

    return rewritten


def _merge_with_existing_package_import(
    tree: ast.Module,
    lines: list[str],
    import_statement: str,
) -> str | None:
    parsed_import = ast.parse(import_statement).body[0]
    if not isinstance(parsed_import, ast.ImportFrom) or parsed_import.module is None:
        return None

    body = getattr(tree, "body", [])
    for stmt in body:
        if not isinstance(stmt, ast.ImportFrom):
            continue
        if stmt.end_lineno is None:
            continue
        if stmt.level != parsed_import.level or stmt.module != parsed_import.module:
            continue

        imported_names = [alias.name for alias in stmt.names]
        new_name = parsed_import.names[0].name
        if new_name in imported_names:
            return None

        imported_names.append(new_name)
        replacement = _format_import_from(stmt.level, stmt.module, imported_names)
        start_lineno = statement_start_lineno(stmt)
        lines[start_lineno - 1 : stmt.end_lineno] = [replacement]

        updated = "".join(lines)
        while "\n\n\n" in updated:
            updated = updated.replace("\n\n\n", "\n\n")
        return updated

    return None


def _format_import_from(level: int, module: str | None, names: list[str]) -> str:
    prefix = "." * level
    module_path = f"{prefix}{module or ''}"
    unique_names = sorted(set(names))
    return f"from {module_path} import {', '.join(unique_names)}\n"


def _format_alias(alias: ast.alias) -> str:
    if alias.asname:
        return f"{alias.name} as {alias.asname}"
    return alias.name


def _import_alias_bound_name(stmt: ast.Import | ast.ImportFrom, alias: ast.alias) -> str:
    if alias.asname:
        return alias.asname
    if isinstance(stmt, ast.Import):
        return alias.name.split(".", 1)[0]
    return alias.name
