from __future__ import annotations

import ast
import difflib
import re
from dataclasses import dataclass
from pathlib import Path

from .models import FileChange
from .paradigm import ParadigmResult
from .rewrite import validate_split_outputs
from .utils import write_text_preserving_newlines

ARCHITECTURE_MARKER = "# Auto-generated by ManaSplice: layered architecture"


@dataclass(slots=True)
class ArchitectureOptions:
    preview: bool = False
    validate: bool = False
    contexts: list[str] | None = None


def transform_project_to_layered_architecture(
    project_root: Path,
    *,
    options: ArchitectureOptions | None = None,
) -> list[ParadigmResult]:
    options = options or ArchitectureOptions()
    project_root = project_root.resolve()
    context_names = options.contexts or infer_layered_context_names(project_root)
    if not context_names:
        context_names = ["core"]

    file_changes: list[FileChange] = []
    for context_name in context_names:
        context_dir = project_root / "contexts" / context_name
        file_changes.extend(
            [
                _change_for_file(context_dir / "__init__.py", ""),
                _change_for_file(context_dir / "domain" / "__init__.py", _domain_init_text(context_name)),
                _change_for_file(context_dir / "domain" / "entities.py", _entities_text(context_name)),
                _change_for_file(context_dir / "domain" / "events.py", _events_text(context_name)),
                _change_for_file(context_dir / "application" / "__init__.py", _application_init_text(context_name)),
                _change_for_file(context_dir / "application" / "ports.py", _ports_text(context_name)),
                _change_for_file(context_dir / "application" / "services.py", _services_text(context_name)),
                _change_for_file(
                    context_dir / "infrastructure" / "__init__.py",
                    _infrastructure_init_text(context_name),
                ),
                _change_for_file(context_dir / "infrastructure" / "repositories.py", _repositories_text(context_name)),
                _change_for_file(context_dir / "presentation" / "__init__.py", _presentation_init_text(context_name)),
                _change_for_file(context_dir / "presentation" / "controllers.py", _controllers_text(context_name)),
            ]
        )

    file_changes.extend(
        [
            _change_for_file(project_root / "contexts" / "__init__.py", ""),
            _change_for_file(project_root / "shared" / "__init__.py", ""),
            _change_for_file(project_root / "shared" / "event_bus.py", _event_bus_text()),
            _change_for_file(project_root / "shared" / "pipeline.py", _pipeline_text()),
        ]
    )
    file_changes = [change for change in file_changes if change.before_text != change.after_text]
    if options.validate:
        validate_split_outputs(file_changes)
    if not options.preview:
        for change in file_changes:
            change.path.parent.mkdir(parents=True, exist_ok=True)
            write_text_preserving_newlines(change.path, change.after_text)
    violations = _lint_layer_dependencies(project_root)

    return [
        ParadigmResult(
            module_file=project_root,
            class_name="LayeredArchitecture",
            function_names=context_names,
            skipped=violations,
            preview=options.preview,
            file_changes=file_changes,
            preview_diffs=_build_preview_diffs(file_changes) if options.preview else [],
        )
    ]


def infer_layered_context_names(project_root: Path) -> list[str]:
    names: set[str] = set()
    ignored = {
        ".git",
        ".venv",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "build",
        "contexts",
        "dist",
        "shared",
    }
    for file_path in project_root.glob("*.py"):
        if file_path.name == "__init__.py" or file_path.name.startswith("."):
            continue
        names.add(_safe_context_name(file_path.stem))
    for directory in project_root.iterdir() if project_root.exists() else []:
        if not directory.is_dir() or directory.name in ignored or directory.name.startswith("."):
            continue
        if (directory / ".msignore").exists():
            continue
        if any(directory.glob("*.py")):
            names.add(_safe_context_name(directory.name))
    return sorted(names)


def _change_for_file(path: Path, after_text: str) -> FileChange:
    before_text = path.read_text(encoding="utf-8") if path.exists() else ""
    return FileChange(path=path, existed_before=path.exists(), before_text=before_text, after_text=after_text)


def _safe_context_name(value: str) -> str:
    normalized = re.sub(r"[^a-zA-Z0-9_]+", "_", value).strip("_").lower()
    return normalized or "core"


def _class_prefix(context_name: str) -> str:
    return "".join(part[:1].upper() + part[1:] for part in context_name.split("_") if part) or "Core"


def _domain_init_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return (
        f"from .entities import {prefix}Aggregate, {prefix}Entity\n"
        f"from .events import {prefix}DomainEvent\n\n"
        f"__all__ = [\"{prefix}Aggregate\", \"{prefix}DomainEvent\", \"{prefix}Entity\"]\n"
    )


def _application_init_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return (
        f"from .ports import {prefix}Repository\n"
        f"from .services import {prefix}Service\n\n"
        f"__all__ = [\"{prefix}Repository\", \"{prefix}Service\"]\n"
    )


def _infrastructure_init_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f"from .repositories import InMemory{prefix}Repository\n\n__all__ = [\"InMemory{prefix}Repository\"]\n"


def _presentation_init_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f"from .controllers import {prefix}Controller\n\n__all__ = [\"{prefix}Controller\"]\n"


def _entities_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Any

from .events import {prefix}DomainEvent


@dataclass(frozen=True, slots=True)
class {prefix}Entity:
    id: str

    def evolve(self, **changes: Any) -> "{prefix}Entity":
        return replace(self, **changes)


@dataclass(frozen=True, slots=True)
class {prefix}Aggregate({prefix}Entity):
    events: tuple[{prefix}DomainEvent, ...] = field(default_factory=tuple)

    def record_event(self, event: {prefix}DomainEvent) -> "{prefix}Aggregate":
        return replace(self, events=(*self.events, event))
'''


def _events_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any
from uuid import uuid4


@dataclass(frozen=True, slots=True)
class {prefix}DomainEvent:
    name: str
    payload: dict[str, Any] = field(default_factory=dict)
    event_id: str = field(default_factory=lambda: str(uuid4()))
    occurred_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
'''


def _services_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from shared.event_bus import EventBus
from shared.pipeline import pipe

from ..domain.entities import {prefix}Aggregate
from ..domain.events import {prefix}DomainEvent
from .ports import {prefix}Repository


@dataclass(slots=True)
class {prefix}Service:
    repository: {prefix}Repository
    event_bus: EventBus[{prefix}DomainEvent]

    def save(self, aggregate: {prefix}Aggregate) -> {prefix}Aggregate:
        saved = self.repository.save(aggregate)
        self.publish(saved.events)
        return saved

    def publish(self, events: Iterable[{prefix}DomainEvent]) -> None:
        for event in events:
            self.event_bus.publish(event)

    def run_pipeline(self, value, *steps):
        return pipe(value, *steps)
'''


def _ports_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from typing import Protocol

from ..domain.entities import {prefix}Aggregate


class {prefix}Repository(Protocol):
    def get(self, aggregate_id: str) -> {prefix}Aggregate | None:
        ...

    def save(self, aggregate: {prefix}Aggregate) -> {prefix}Aggregate:
        ...
'''


def _repositories_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from dataclasses import dataclass, field

from ..application.ports import {prefix}Repository
from ..domain.entities import {prefix}Aggregate


@dataclass(slots=True)
class InMemory{prefix}Repository({prefix}Repository):
    _items: dict[str, {prefix}Aggregate] = field(default_factory=dict)

    def get(self, aggregate_id: str) -> {prefix}Aggregate | None:
        return self._items.get(aggregate_id)

    def save(self, aggregate: {prefix}Aggregate) -> {prefix}Aggregate:
        self._items[aggregate.id] = aggregate
        return aggregate
'''


def _controllers_text(context_name: str) -> str:
    prefix = _class_prefix(context_name)
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from dataclasses import dataclass

from ..application.services import {prefix}Service


@dataclass(slots=True)
class {prefix}Controller:
    service: {prefix}Service

    def handle(self, request):
        return request
'''


def _event_bus_text() -> str:
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from collections import defaultdict
from collections.abc import Callable
from typing import Generic, TypeVar

EventT = TypeVar("EventT")


class EventBus(Generic[EventT]):
    def __init__(self) -> None:
        self._handlers: dict[str, list[Callable[[EventT], None]]] = defaultdict(list)

    def subscribe(self, event_name: str, handler: Callable[[EventT], None]) -> None:
        self._handlers[event_name].append(handler)

    def publish(self, event: EventT) -> None:
        event_name = getattr(event, "name", event.__class__.__name__)
        for handler in tuple(self._handlers[event_name]):
            handler(event)
'''


def _pipeline_text() -> str:
    return f'''{ARCHITECTURE_MARKER}
from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from typing import Generic, TypeVar

InT = TypeVar("InT")
OutT = TypeVar("OutT")


@dataclass(frozen=True, slots=True)
class Pipeline(Generic[InT, OutT]):
    steps: tuple[Callable[..., object], ...]

    def then(self, step: Callable[..., object]) -> "Pipeline[InT, OutT]":
        return Pipeline((*self.steps, step))

    def __call__(self, value: InT) -> OutT:
        result: object = value
        for step in self.steps:
            result = step(result)
        return result  # type: ignore[return-value]


def pipe(value: InT, *steps: Callable[..., object]) -> OutT:
    return Pipeline[InT, OutT](steps)(value)
'''


def _lint_layer_dependencies(project_root: Path) -> dict[str, str]:
    contexts_root = project_root / "contexts"
    if not contexts_root.exists():
        return {}
    violations: dict[str, str] = {}
    for file_path in contexts_root.rglob("*.py"):
        if _is_ignored(file_path, project_root):
            continue
        location = _layer_location(file_path, project_root)
        if location is None:
            continue
        context_name, layer_name = location
        for imported_module, line_number in _iter_imported_modules(file_path, project_root):
            violation = _layer_violation(context_name, layer_name, imported_module)
            if violation:
                key = f"{file_path.relative_to(project_root)}:{line_number}"
                violations[key] = violation

    for file_path in (project_root / "shared").rglob("*.py") if (project_root / "shared").exists() else []:
        if _is_ignored(file_path, project_root):
            continue
        for imported_module, line_number in _iter_imported_modules(file_path, project_root):
            if imported_module.startswith("contexts."):
                key = f"{file_path.relative_to(project_root)}:{line_number}"
                violations[key] = "shared code must not import bounded contexts"
    return violations


def _layer_location(file_path: Path, project_root: Path) -> tuple[str, str] | None:
    try:
        parts = file_path.relative_to(project_root).parts
    except ValueError:
        return None
    if len(parts) < 4 or parts[0] != "contexts":
        return None
    context_name = parts[1]
    layer_name = parts[2]
    if layer_name not in {"domain", "application", "infrastructure", "presentation"}:
        return None
    return context_name, layer_name


def _iter_imported_modules(file_path: Path, project_root: Path) -> list[tuple[str, int]]:
    try:
        tree = ast.parse(file_path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError):
        return []
    imports: list[tuple[str, int]] = []
    current_module = _module_name(file_path, project_root)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imports.extend((alias.name, node.lineno) for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            imports.append((_resolve_import_from(current_module, node), node.lineno))
    return imports


def _module_name(file_path: Path, project_root: Path) -> str:
    relative = file_path.relative_to(project_root).with_suffix("")
    return ".".join(part for part in relative.parts if part != "__init__")


def _resolve_import_from(current_module: str, node: ast.ImportFrom) -> str:
    if node.level == 0:
        return node.module or ""
    package_parts = current_module.split(".")[:-1]
    if node.level > 1:
        package_parts = package_parts[: -(node.level - 1)]
    if node.module:
        package_parts.extend(part for part in node.module.split(".") if part)
    return ".".join(package_parts)


def _layer_violation(context_name: str, layer_name: str, imported_module: str) -> str:
    imported_parts = imported_module.split(".")
    if len(imported_parts) < 3 or imported_parts[0] != "contexts":
        return ""
    imported_context = imported_parts[1]
    imported_layer = imported_parts[2]
    if imported_context != context_name:
        return f"bounded context '{context_name}' must not import context '{imported_context}'"
    forbidden_layers = {
        "domain": {"application", "infrastructure", "presentation"},
        "application": {"infrastructure", "presentation"},
        "infrastructure": {"presentation"},
        "presentation": {"infrastructure"},
    }
    if imported_layer in forbidden_layers.get(layer_name, set()):
        return f"{layer_name} layer must not import {imported_layer} layer"
    return ""


def _is_ignored(file_path: Path, project_root: Path) -> bool:
    current = file_path.parent.resolve()
    project_root = project_root.resolve()
    while True:
        if (current / ".msignore").exists():
            return True
        if current == project_root or current.parent == current:
            return False
        current = current.parent


def _build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        diff_lines = list(
            difflib.unified_diff(
                change.before_text.splitlines(),
                change.after_text.splitlines(),
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs
