from __future__ import annotations

import ast
import difflib
from collections.abc import Sequence
from pathlib import Path

import libcst as cst
from libcst.metadata import CodeRange, MetadataWrapper, PositionProvider

from .exceptions import FunctionExtractionError
from .models import FileChange


def extract_lines(source_text: str, start_lineno: int, end_lineno: int) -> str:
    module, positions = _module_with_top_level_positions(source_text)
    for node, position in positions.items():
        if isinstance(node, cst.FunctionDef) and _matches_ast_function_range(position, start_lineno, end_lineno):
            return module.code_for_node(node)

    raise FunctionExtractionError(f"Could not find a top-level function at lines {start_lineno}-{end_lineno}.")


def build_import_block(
    imports: list[ast.stmt],
    source_text: str,
    package_mode: bool,
    output_package: str,
    required_import_names: set[str],
) -> str:
    lines = source_text.splitlines(keepends=True)
    blocks: list[str] = []

    for stmt in imports:
        if isinstance(stmt, ast.ImportFrom) and stmt.module == "__future__":
            blocks.append("".join(lines[stmt.lineno - 1 : stmt.end_lineno]).rstrip())
            continue

        filtered = _filter_import(stmt, source_text, required_import_names)
        if filtered is None:
            continue
        if isinstance(stmt, ast.ImportFrom) and stmt.module == output_package:
            blocks.extend(_rewrite_package_import(filtered, package_mode, output_package))
            continue
        blocks.append(filtered)

    if not blocks:
        return ""
    return "\n".join(blocks) + "\n\n"


def compose_new_module_text(
    source_path: Path,
    import_block: str,
    dependency_block: str,
    function_block: str,
) -> str:
    header = f'"""Auto-generated by ManaSplice from {source_path.name}."""\n\n'
    function_block = function_block.strip() + "\n"
    return header + import_block + dependency_block + function_block


def updated_package_exports(existing: str, function_name: str) -> str:
    export_line = f"from .{function_name} import {function_name}\n"
    lines = existing.splitlines(keepends=True)

    if export_line in lines:
        return existing

    lines.append(export_line)
    lines = sorted(set(lines), key=str.casefold)
    return "".join(lines)


def updated_package_exports_for_group(existing: str, group_module_name: str, function_names: list[str]) -> str:
    names_str = ", ".join(sorted(function_names))
    export_line = f"from .{group_module_name} import {names_str}\n"

    lines = existing.splitlines(keepends=True)
    filtered = [
        line for line in lines if not any(line.strip() == f"from .{name} import {name}" for name in function_names)
    ]
    if export_line in filtered:
        return "".join(filtered)

    filtered.append(export_line)
    filtered = sorted(set(filtered), key=str.casefold)
    return "".join(filtered)


def remove_function_block(source_text: str, start_lineno: int, end_lineno: int) -> str:
    return remove_function_blocks(source_text, [(start_lineno, end_lineno)])


def remove_function_blocks(source_text: str, ranges: list[tuple[int, int]]) -> str:
    module, positions = _module_with_top_level_positions(source_text)
    ranges_to_remove = set(ranges)
    updated_body: list[cst.BaseStatement] = []
    removed_ranges: set[tuple[int, int]] = set()

    for stmt in module.body:
        position = positions.get(stmt)
        if isinstance(stmt, cst.FunctionDef) and position is not None:
            matched_range = _matched_ast_range(position, ranges_to_remove)
            if matched_range is not None:
                removed_ranges.add(matched_range)
                continue
        updated_body.append(stmt)

    missing_ranges = ranges_to_remove - removed_ranges
    if missing_ranges:
        formatted = ", ".join(f"{start}-{end}" for start, end in sorted(missing_ranges))
        raise FunctionExtractionError(f"Could not remove top-level function range(s): {formatted}.")

    return _normalize_rewritten_source(module.with_changes(body=updated_body).code)


def compute_replacement_import(package_mode: bool, output_package: str, function_name: str) -> str:
    if package_mode:
        return f"from .{output_package} import {function_name}"
    return f"from {output_package} import {function_name}"


def compute_group_import_statement(package_mode: bool, output_package: str, function_names: list[str]) -> str:
    names_str = ", ".join(sorted(function_names))
    if package_mode:
        return f"from .{output_package} import {names_str}"
    return f"from {output_package} import {names_str}"


def insert_import(source_text: str, import_statement: str) -> str:
    module = cst.parse_module(source_text)
    import_node = _parse_simple_import(import_statement, module)

    merged_module = _merge_with_existing_package_import(module, import_node)
    if merged_module is not None:
        return _normalize_rewritten_source(merged_module.code)

    body: list[cst.BaseStatement] = list(module.body)
    insert_at = _import_insert_index(body)
    body.insert(insert_at, import_node)
    return _normalize_rewritten_source(module.with_changes(body=body).code)


def validate_output_package(output_package: str) -> None:
    parts = output_package.split(".")
    if not output_package or any(not part.isidentifier() for part in parts):
        raise FunctionExtractionError(
            f"Invalid output package '{output_package}'. "
            "Use a dotted Python package path like 'modules' or 'generated'."
        )


def validate_split_outputs(file_changes: list[FileChange]) -> None:
    for change in file_changes:
        if not change.after_text:
            continue
        try:
            ast.parse(change.after_text)
        except SyntaxError as exc:
            raise FunctionExtractionError(
                f"Validation failed for '{change.path.name}': {exc.msg} at line {exc.lineno}."
            ) from exc


def build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        before = change.before_text.splitlines()
        after = change.after_text.splitlines()
        diff_lines = list(
            difflib.unified_diff(
                before,
                after,
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs


def _filter_import(stmt: ast.stmt, source_text: str, required_import_names: set[str]) -> str | None:
    if not isinstance(stmt, (ast.Import, ast.ImportFrom)) or stmt.end_lineno is None:
        return None
    if isinstance(stmt, ast.ImportFrom) and any(alias.name == "*" for alias in stmt.names):
        return _extract_source_range(source_text, stmt.lineno, stmt.end_lineno).rstrip()

    kept = [alias for alias in stmt.names if _import_alias_bound_name(stmt, alias) in required_import_names]
    if not kept:
        return None

    if isinstance(stmt, ast.Import):
        names = ", ".join(_format_alias(alias) for alias in kept)
        return f"import {names}"

    module_path = "." * stmt.level + (stmt.module or "")
    names = ", ".join(_format_alias(alias) for alias in kept)
    return f"from {module_path} import {names}"


def _rewrite_package_import(import_text: str, package_mode: bool, output_package: str) -> list[str]:
    stmt = ast.parse(import_text).body[0]
    if not isinstance(stmt, ast.ImportFrom):
        return [import_text]

    rewritten: list[str] = []
    for alias in sorted(stmt.names, key=lambda item: item.name.casefold()):
        import_name = alias.name
        if alias.asname is None:
            if package_mode:
                rewritten.append(f"from .{import_name} import {import_name}")
            else:
                rewritten.append(f"from {output_package}.{import_name} import {import_name}")
            continue

        if package_mode:
            rewritten.append(f"from .{import_name} import {import_name} as {alias.asname}")
        else:
            rewritten.append(f"from {output_package}.{import_name} import {import_name} as {alias.asname}")

    return rewritten


def _format_alias(alias: ast.alias) -> str:
    if alias.asname:
        return f"{alias.name} as {alias.asname}"
    return alias.name


def _import_alias_bound_name(stmt: ast.Import | ast.ImportFrom, alias: ast.alias) -> str:
    if alias.asname:
        return alias.asname
    if isinstance(stmt, ast.Import):
        return alias.name.split(".", 1)[0]
    return alias.name


def _module_with_top_level_positions(source_text: str) -> tuple[cst.Module, dict[cst.CSTNode, CodeRange]]:
    wrapper = MetadataWrapper(cst.parse_module(source_text))
    positions = wrapper.resolve(PositionProvider)
    return wrapper.module, {stmt: positions[stmt] for stmt in wrapper.module.body if stmt in positions}


def _matches_ast_function_range(position: CodeRange, start_lineno: int, end_lineno: int) -> bool:
    return start_lineno <= position.start.line <= end_lineno and position.end.line == end_lineno


def _matched_ast_range(position: CodeRange, ranges: set[tuple[int, int]]) -> tuple[int, int] | None:
    for start_lineno, end_lineno in ranges:
        if _matches_ast_function_range(position, start_lineno, end_lineno):
            return start_lineno, end_lineno
    return None


def _parse_simple_import(import_statement: str, module: cst.Module) -> cst.SimpleStatementLine:
    parsed = cst.parse_statement(import_statement + "\n", config=module.config_for_parsing)
    if not isinstance(parsed, cst.SimpleStatementLine):
        raise FunctionExtractionError(f"Replacement import is not a simple import: {import_statement}")
    if len(parsed.body) != 1 or not isinstance(parsed.body[0], cst.ImportFrom):
        raise FunctionExtractionError(f"Replacement import is not a from-import: {import_statement}")
    return parsed


def _merge_with_existing_package_import(
    module: cst.Module,
    import_node: cst.SimpleStatementLine,
) -> cst.Module | None:
    import_from = import_node.body[0]
    if not isinstance(import_from, cst.ImportFrom) or not isinstance(import_from.names, Sequence):
        return None

    import_key = _import_from_key(import_from)
    if import_key is None:
        return None

    new_alias = import_from.names[0]
    if not isinstance(new_alias, cst.ImportAlias):
        return None
    new_name = _dotted_name_to_str(new_alias.name)

    body = list(module.body)
    for index, stmt in enumerate(body):
        existing = _single_import_from(stmt)
        if existing is None or _import_from_key(existing) != import_key:
            continue
        if not isinstance(existing.names, Sequence):
            continue

        existing_names = [_dotted_name_to_str(alias.name) for alias in existing.names]
        if new_name in existing_names:
            return None

        replacement = _format_cst_import_from(existing, [*existing_names, new_name])
        body[index] = cst.parse_statement(replacement, config=module.config_for_parsing)
        return module.with_changes(body=body)

    return None


def _single_import_from(stmt: cst.BaseStatement) -> cst.ImportFrom | None:
    if not isinstance(stmt, cst.SimpleStatementLine) or len(stmt.body) != 1:
        return None
    small_stmt = stmt.body[0]
    if isinstance(small_stmt, cst.ImportFrom):
        return small_stmt
    return None


def _import_from_key(node: cst.ImportFrom) -> tuple[int, str] | None:
    module_name = _import_module_name(node)
    if module_name is None:
        return None
    return (len(node.relative), module_name)


def _import_module_name(node: cst.ImportFrom) -> str | None:
    if node.module is None:
        return ""
    return _dotted_name_to_str(node.module)


def _dotted_name_to_str(node: cst.BaseExpression) -> str:
    if isinstance(node, cst.Name):
        return node.value
    if isinstance(node, cst.Attribute):
        return f"{_dotted_name_to_str(node.value)}.{node.attr.value}"
    raise FunctionExtractionError("Unsupported import name shape.")


def _format_cst_import_from(node: cst.ImportFrom, names: list[str]) -> str:
    module_name = _import_module_name(node)
    if module_name is None:
        raise FunctionExtractionError("Unsupported import statement shape.")
    prefix = "." * len(node.relative)
    unique_names = sorted(set(names))
    return f"from {prefix}{module_name} import {', '.join(unique_names)}\n"


def _import_insert_index(body: list[cst.BaseStatement]) -> int:
    insert_at = 0
    if body and _is_module_docstring(body[0]):
        insert_at = 1

    for index, stmt in enumerate(body):
        if _single_import(stmt) is not None or _single_import_from(stmt) is not None:
            insert_at = index + 1

    return insert_at


def _single_import(stmt: cst.BaseStatement) -> cst.Import | None:
    if not isinstance(stmt, cst.SimpleStatementLine) or len(stmt.body) != 1:
        return None
    small_stmt = stmt.body[0]
    if isinstance(small_stmt, cst.Import):
        return small_stmt
    return None


def _is_module_docstring(stmt: cst.BaseStatement) -> bool:
    if not isinstance(stmt, cst.SimpleStatementLine) or len(stmt.body) != 1:
        return False
    expr = stmt.body[0]
    return isinstance(expr, cst.Expr) and isinstance(expr.value, cst.SimpleString)


def _normalize_rewritten_source(source_text: str) -> str:
    updated = source_text
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated.lstrip("\n")


def _extract_source_range(source_text: str, start_lineno: int, end_lineno: int) -> str:
    lines = source_text.splitlines(keepends=True)
    return "".join(lines[start_lineno - 1 : end_lineno])
