from __future__ import annotations

import ast
import copy
import difflib
import fnmatch
from dataclasses import dataclass
from pathlib import Path

from .analysis import statement_start_lineno
from .exceptions import PySplitError
from .models import FileChange
from .paradigm import ParadigmOptions, ParadigmResult
from .rewrite import validate_split_outputs
from .utils import read_python_source, write_text_preserving_newlines

SEMANTIC_OOP_MARKER = "# Auto-generated by ManaSplice: semantic OOP class"


@dataclass(slots=True)
class _SemanticFunction:
    node: ast.FunctionDef | ast.AsyncFunctionDef
    start_lineno: int
    end_lineno: int
    skip_reason: str


def transform_module_to_semantic_oop(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text = read_python_source(file_path)
    try:
        tree = ast.parse(source_text)
    except SyntaxError as exc:
        raise PySplitError(f"Could not parse '{file_path}': {exc}") from exc

    class_name = options.class_name or _default_class_name(file_path)
    if not class_name.isidentifier():
        raise PySplitError(f"Invalid class name '{class_name}'.")
    if _has_top_level_name(tree, class_name):
        raise PySplitError(f"Class '{class_name}' already exists in '{file_path}'.")

    instance_name = _default_instance_name(class_name)
    if _has_top_level_name(tree, instance_name):
        raise PySplitError(f"Name '{instance_name}' already exists in '{file_path}'.")

    candidates = _collect_semantic_candidates(
        tree,
        options,
        max_lineno=_first_generated_marker_lineno(source_text),
    )
    selected = [candidate for candidate in candidates if not candidate.skip_reason]
    skipped = {candidate.node.name: candidate.skip_reason for candidate in candidates if candidate.skip_reason}
    if not selected:
        return ParadigmResult(
            module_file=file_path,
            class_name=class_name,
            function_names=[],
            skipped=skipped,
            preview=options.preview,
            file_changes=[],
            preview_diffs=[],
        )

    top_level_state = _top_level_state_names(tree)
    method_names = {candidate.node.name for candidate in selected}
    state_names = _infer_instance_state(selected, top_level_state)
    updated_source = _rewrite_semantic_oop_source(
        source_text,
        tree,
        selected,
        class_name=class_name,
        instance_name=instance_name,
        method_names=method_names,
        state_names=state_names,
    )
    file_changes = [FileChange(file_path, True, source_text, updated_source)]
    if options.validate:
        validate_split_outputs(file_changes)
    if not options.preview:
        write_text_preserving_newlines(file_path, updated_source)

    return ParadigmResult(
        module_file=file_path,
        class_name=class_name,
        function_names=[candidate.node.name for candidate in selected],
        skipped=skipped,
        preview=options.preview,
        file_changes=file_changes,
        preview_diffs=_build_preview_diffs(file_changes) if options.preview else [],
    )


def _collect_semantic_candidates(
    tree: ast.Module,
    options: ParadigmOptions,
    *,
    max_lineno: int | None,
) -> list[_SemanticFunction]:
    candidates: list[_SemanticFunction] = []
    include_patterns = options.include_patterns or []
    exclude_patterns = options.exclude_patterns or []
    top_level_state = _top_level_state_names(tree)
    overloaded_names = {
        stmt.name
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)) and _is_overload_function(stmt)
    }
    eager_references = _collect_eager_top_level_references(tree)

    for stmt in tree.body:
        if not isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if max_lineno is not None and statement_start_lineno(stmt) >= max_lineno:
            continue
        if options.public_only and stmt.name.startswith("_"):
            continue
        if include_patterns and not any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in include_patterns):
            continue
        if exclude_patterns and any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in exclude_patterns):
            continue
        if stmt.end_lineno is None:
            raise PySplitError(f"Could not determine end line for function '{stmt.name}'.")

        skip_reason = ""
        if stmt.decorator_list:
            skip_reason = "decorated functions are left unchanged"
        elif stmt.name in overloaded_names:
            skip_reason = "overloaded functions are left unchanged"
        elif stmt.name in eager_references:
            skip_reason = "functions referenced during module initialization are left unchanged"
        elif _uses_dynamic_code_execution(stmt):
            skip_reason = "functions using dynamic code execution are left unchanged"
        elif _global_statement_names(stmt):
            skip_reason = "functions with global statements are left unchanged"
        elif _contains_nested_definition(stmt):
            skip_reason = "functions with nested definitions are left unchanged"
        elif _signature_references_state(stmt, top_level_state):
            skip_reason = "functions with module-state defaults are left unchanged"

        candidates.append(
            _SemanticFunction(
                node=stmt,
                start_lineno=statement_start_lineno(stmt),
                end_lineno=stmt.end_lineno,
                skip_reason=skip_reason,
            )
        )

    return candidates


def _rewrite_semantic_oop_source(
    source_text: str,
    tree: ast.Module,
    candidates: list[_SemanticFunction],
    *,
    class_name: str,
    instance_name: str,
    method_names: set[str],
    state_names: list[str],
) -> str:
    candidates = sorted(candidates, key=lambda candidate: candidate.start_lineno)
    lines = source_text.splitlines(keepends=True)
    class_block = _build_semantic_class_block(candidates, class_name, instance_name, method_names, state_names)
    insertion_lineno = _generated_class_insertion_lineno(tree, len(lines))

    output: list[str] = []
    cursor = 1
    inserted_class = False
    for candidate in candidates:
        if not inserted_class and cursor <= insertion_lineno <= candidate.start_lineno:
            output.extend(lines[cursor - 1 : insertion_lineno - 1])
            output.append(class_block)
            cursor = insertion_lineno
            inserted_class = True
        output.extend(lines[cursor - 1 : candidate.start_lineno - 1])
        output.append(_build_instance_wrapper(candidate.node, instance_name))
        cursor = candidate.end_lineno + 1
    if not inserted_class:
        output.extend(lines[cursor - 1 : insertion_lineno - 1])
        output.append(class_block)
        cursor = insertion_lineno
    output.extend(lines[cursor - 1 :])

    return _normalize_rewritten_source("".join(output))


def _build_semantic_class_block(
    candidates: list[_SemanticFunction],
    class_name: str,
    instance_name: str,
    method_names: set[str],
    state_names: list[str],
) -> str:
    class_parts = [SEMANTIC_OOP_MARKER, f"class {class_name}:"]
    if state_names:
        parameters = ", ".join(f"{_attribute_name(name)}={name}" for name in state_names)
        class_parts.append(f"    def __init__(self, {parameters}):")
        for state_name in state_names:
            attribute_name = _attribute_name(state_name)
            class_parts.append(f"        self.{attribute_name} = {attribute_name}")
        class_parts.append("")

    for candidate in candidates:
        method_source = _build_instance_method_source(candidate.node, method_names, set(state_names))
        class_parts.extend("    " + line if line else "" for line in method_source.splitlines())
        class_parts.append("")

    if not candidates and not state_names:
        class_parts.append("    pass")
    class_parts.append("")
    class_parts.append(f"{instance_name} = {class_name}()")
    return "\n".join(class_parts).rstrip() + "\n\n"


def _build_instance_method_source(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    method_names: set[str],
    state_names: set[str],
) -> str:
    method_node = copy.deepcopy(node)
    method_node.decorator_list = []
    method_node.args.args.insert(0, ast.arg(arg="self"))
    local_names = _function_local_names(method_node)
    transformer = _InstanceMethodTransformer(
        method_names=method_names,
        state_names=state_names,
        local_names=local_names,
    )
    method_node = transformer.visit(method_node)
    ast.fix_missing_locations(method_node)
    return ast.unparse(method_node)


def _build_instance_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef, instance_name: str) -> str:
    async_prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    await_prefix = "await " if isinstance(node, ast.AsyncFunctionDef) else ""
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    signature = ast.unparse(node.args)
    call_args = _call_arguments(node.args)
    call = f"{await_prefix}{instance_name}.{node.name}({call_args})"
    return f"{async_prefix}def {node.name}({signature}){returns}:\n    return {call}\n\n"


class _InstanceMethodTransformer(ast.NodeTransformer):
    def __init__(self, *, method_names: set[str], state_names: set[str], local_names: set[str]) -> None:
        self._method_names = method_names
        self._state_names = state_names
        self._local_names = local_names
        self._state_attributes = {name: _attribute_name(name) for name in state_names}

    def visit_Call(self, node: ast.Call) -> ast.AST:
        visited = self.generic_visit(node)
        if (
            isinstance(visited, ast.Call)
            and isinstance(visited.func, ast.Name)
            and visited.func.id in self._method_names
        ):
            visited.func = ast.Attribute(
                value=ast.Name(id="self", ctx=ast.Load()),
                attr=visited.func.id,
                ctx=ast.Load(),
            )
        return visited

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if (
            isinstance(node.ctx, ast.Load)
            and node.id in self._state_names
            and node.id not in self._local_names
        ):
            return ast.copy_location(
                ast.Attribute(
                    value=ast.Name(id="self", ctx=ast.Load()),
                    attr=self._state_attributes[node.id],
                    ctx=node.ctx,
                ),
                node,
            )
        return node


def _infer_instance_state(candidates: list[_SemanticFunction], top_level_state: set[str]) -> list[str]:
    used_state: set[str] = set()
    for candidate in candidates:
        local_names = _function_local_names(candidate.node)
        for node in ast.walk(candidate.node):
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                if node.id in top_level_state and node.id not in local_names:
                    used_state.add(node.id)
    return sorted(used_state)


def _top_level_state_names(tree: ast.Module) -> set[str]:
    names: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            names.add(stmt.target.id)
    return names


def _function_local_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names = {arg.arg for arg in [*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs]}
    if node.args.vararg is not None:
        names.add(node.args.vararg.arg)
    if node.args.kwarg is not None:
        names.add(node.args.kwarg.arg)
    for child in ast.walk(node):
        if isinstance(child, ast.Name) and isinstance(child.ctx, (ast.Store, ast.Del)):
            names.add(child.id)
        elif isinstance(child, (ast.For, ast.AsyncFor)):
            names.update(_stored_names(child.target))
        elif isinstance(child, ast.With):
            for item in child.items:
                if item.optional_vars is not None:
                    names.update(_stored_names(item.optional_vars))
        elif isinstance(child, ast.ExceptHandler) and child.name is not None:
            names.add(child.name)
    names.discard("self")
    return names


def _stored_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name)}


def _global_statement_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names: set[str] = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Global):
            names.update(child.names)
    return names


def _contains_nested_definition(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for child in ast.iter_child_nodes(node):
        for nested in ast.walk(child):
            if isinstance(nested, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)):
                return True
    return False


def _signature_references_state(node: ast.FunctionDef | ast.AsyncFunctionDef, state_names: set[str]) -> bool:
    signature_nodes: list[ast.AST] = [
        *node.args.defaults,
        *(default for default in node.args.kw_defaults if default is not None),
    ]
    signature_nodes.extend(arg.annotation for arg in _all_arguments(node.args) if arg.annotation is not None)
    if node.returns is not None:
        signature_nodes.append(node.returns)
    return any(name in state_names for signature_node in signature_nodes for name in _loaded_names(signature_node))


def _all_arguments(args: ast.arguments) -> list[ast.arg]:
    return [*args.posonlyargs, *args.args, *args.kwonlyargs]


def _first_generated_marker_lineno(source_text: str) -> int | None:
    marker_lines: list[int] = []
    for marker in (
        SEMANTIC_OOP_MARKER,
        "# Auto-generated by ManaSplice: functional facade",
        "# Auto-generated by ManaSplice: event facade",
        "# Auto-generated by ManaSplice: OOP class",
        "# Auto-generated by ManaSplice: procedural compatibility class",
    ):
        index = source_text.find(marker)
        if index >= 0:
            marker_lines.append(source_text.count("\n", 0, index) + 1)
    return min(marker_lines) if marker_lines else None


def _collect_eager_top_level_references(tree: ast.Module) -> set[str]:
    references: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if _is_main_guard(stmt):
            continue
        references.update(_loaded_names(stmt))
    return references


def _loaded_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load)}


def _uses_dynamic_code_execution(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    dynamic_builtins = {"compile", "eval", "exec"}
    return any(
        isinstance(child, ast.Call) and isinstance(child.func, ast.Name) and child.func.id in dynamic_builtins
        for child in ast.walk(node)
    )


def _generated_class_insertion_lineno(tree: ast.Module, line_count: int) -> int:
    for stmt in tree.body:
        if _is_main_guard(stmt):
            return statement_start_lineno(stmt)
    return line_count + 1


def _is_main_guard(stmt: ast.stmt) -> bool:
    if not isinstance(stmt, ast.If):
        return False
    test = stmt.test
    if not isinstance(test, ast.Compare) or len(test.ops) != 1 or len(test.comparators) != 1:
        return False
    if not isinstance(test.ops[0], ast.Eq):
        return False
    left = test.left
    right = test.comparators[0]
    return (
        isinstance(left, ast.Name)
        and left.id == "__name__"
        and isinstance(right, ast.Constant)
        and right.value == "__main__"
    )


def _call_arguments(args: ast.arguments) -> str:
    names: list[str] = []
    names.extend(arg.arg for arg in args.posonlyargs)
    names.extend(arg.arg for arg in args.args)
    if args.vararg is not None:
        names.append(f"*{args.vararg.arg}")
    names.extend(f"{arg.arg}={arg.arg}" for arg in args.kwonlyargs)
    if args.kwarg is not None:
        names.append(f"**{args.kwarg.arg}")
    return ", ".join(names)


def _default_class_name(file_path: Path) -> str:
    stem = file_path.stem
    if stem == "__init__":
        stem = file_path.parent.name
    words = [word for word in stem.replace("-", "_").split("_") if word]
    base = "".join(word[:1].upper() + word[1:] for word in words) or "Module"
    return f"{base}Service"


def _default_instance_name(class_name: str) -> str:
    words: list[str] = []
    current = ""
    for character in class_name:
        if character.isupper() and current:
            words.append(current)
            current = character
        else:
            current += character
    if current:
        words.append(current)
    return "_DEFAULT_" + "_".join(word.upper() for word in words)


def _attribute_name(name: str) -> str:
    return name.lower()


def _has_top_level_name(tree: ast.Module, name: str) -> bool:
    for stmt in tree.body:
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and stmt.name == name:
            return True
        if isinstance(stmt, ast.Assign) and name in _assigned_names(stmt):
            return True
        if isinstance(stmt, ast.AnnAssign) and name in _assigned_names(stmt):
            return True
    return False


def _assigned_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Store)}


def _is_overload_function(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(_decorator_name(decorator) == "overload" for decorator in node.decorator_list)


def _decorator_name(node: ast.expr) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Call):
        return _decorator_name(node.func)
    return ""


def _normalize_rewritten_source(source_text: str) -> str:
    updated = source_text
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated.lstrip("\n")


def _build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        diff_lines = list(
            difflib.unified_diff(
                change.before_text.splitlines(),
                change.after_text.splitlines(),
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs
