from __future__ import annotations

import ast
import copy
import difflib
import fnmatch
from dataclasses import dataclass
from pathlib import Path

from .analysis import statement_start_lineno
from .exceptions import PySplitError
from .models import FileChange
from .paradigm import ParadigmOptions, ParadigmResult
from .rewrite import validate_split_outputs
from .utils import read_python_source, write_text_preserving_newlines

SEMANTIC_OOP_MARKER = "# Auto-generated by ManaSplice: semantic OOP class"


@dataclass(slots=True)
class _SemanticFunction:
    node: ast.FunctionDef | ast.AsyncFunctionDef
    start_lineno: int
    end_lineno: int
    skip_reason: str


@dataclass(slots=True)
class _RecordGroup:
    prefix: str
    class_name: str
    entity_base_name: str
    instance_arg: str
    methods: list[_SemanticFunction]
    factory: _SemanticFunction | None
    fields: list[str]
    field_defaults: dict[str, ast.expr]


def transform_module_to_semantic_oop(file_path: Path, *, options: ParadigmOptions | None = None) -> ParadigmResult:
    options = options or ParadigmOptions()
    source_text = read_python_source(file_path)
    try:
        tree = ast.parse(source_text)
    except SyntaxError as exc:
        raise PySplitError(f"Could not parse '{file_path}': {exc}") from exc

    class_name = options.class_name or _default_class_name(file_path)
    if not class_name.isidentifier():
        raise PySplitError(f"Invalid class name '{class_name}'.")
    if _has_top_level_name(tree, class_name):
        raise PySplitError(f"Class '{class_name}' already exists in '{file_path}'.")

    instance_name = _default_instance_name(class_name)
    if _has_top_level_name(tree, instance_name):
        raise PySplitError(f"Name '{instance_name}' already exists in '{file_path}'.")

    candidates = _collect_semantic_candidates(
        tree,
        options,
        max_lineno=_first_generated_marker_lineno(source_text),
    )
    selected = [candidate for candidate in candidates if not candidate.skip_reason]
    skipped = {candidate.node.name: candidate.skip_reason for candidate in candidates if candidate.skip_reason}
    if not selected:
        return ParadigmResult(
            module_file=file_path,
            class_name=class_name,
            function_names=[],
            skipped=skipped,
            preview=options.preview,
            file_changes=[],
            preview_diffs=[],
        )

    record_groups = _infer_record_groups(selected, class_name if options.class_name else None)
    if record_groups:
        for group in record_groups:
            if _has_top_level_name(tree, group.class_name):
                raise PySplitError(f"Class '{group.class_name}' already exists in '{file_path}'.")
            if group.entity_base_name and _has_top_level_name(tree, group.entity_base_name):
                raise PySplitError(f"Class '{group.entity_base_name}' already exists in '{file_path}'.")
            adapter_name = _record_adapter_name(group.prefix)
            if _has_top_level_name(tree, adapter_name):
                raise PySplitError(f"Name '{adapter_name}' already exists in '{file_path}'.")

        grouped_candidates = [candidate for group in record_groups for candidate in _record_group_candidates(group)]
        grouped_names = {candidate.node.name for candidate in grouped_candidates}
        skipped.update(
            {
                candidate.node.name: "no cohesive record-style class could be inferred"
                for candidate in selected
                if candidate.node.name not in grouped_names
            }
        )
        updated_source = _rewrite_record_oop_source(source_text, tree, record_groups)
        file_changes = [FileChange(file_path, True, source_text, updated_source)]
        if options.validate:
            validate_split_outputs(file_changes)
        if not options.preview:
            write_text_preserving_newlines(file_path, updated_source)

        return ParadigmResult(
            module_file=file_path,
            class_name=", ".join(group.class_name for group in record_groups),
            function_names=[candidate.node.name for candidate in grouped_candidates],
            skipped=skipped,
            preview=options.preview,
            file_changes=file_changes,
            preview_diffs=_build_preview_diffs(file_changes) if options.preview else [],
        )

    top_level_state = _top_level_state_names(tree)
    service_candidates, service_skips = _select_service_candidates(
        selected,
        top_level_state,
        file_path=file_path,
        explicit_class_name=bool(options.class_name),
    )
    skipped.update(service_skips)
    if not service_candidates:
        return ParadigmResult(
            module_file=file_path,
            class_name=class_name,
            function_names=[],
            skipped=skipped,
            preview=options.preview,
            file_changes=[],
            preview_diffs=[],
        )

    method_names = {candidate.node.name for candidate in service_candidates}
    state_names = _infer_instance_state(service_candidates, top_level_state)
    updated_source = _rewrite_semantic_oop_source(
        source_text,
        tree,
        service_candidates,
        class_name=class_name,
        instance_name=instance_name,
        method_names=method_names,
        state_names=state_names,
    )
    file_changes = [FileChange(file_path, True, source_text, updated_source)]
    if options.validate:
        validate_split_outputs(file_changes)
    if not options.preview:
        write_text_preserving_newlines(file_path, updated_source)

    return ParadigmResult(
        module_file=file_path,
        class_name=class_name,
        function_names=[candidate.node.name for candidate in service_candidates],
        skipped=skipped,
        preview=options.preview,
        file_changes=file_changes,
        preview_diffs=_build_preview_diffs(file_changes) if options.preview else [],
    )


def _collect_semantic_candidates(
    tree: ast.Module,
    options: ParadigmOptions,
    *,
    max_lineno: int | None,
) -> list[_SemanticFunction]:
    candidates: list[_SemanticFunction] = []
    include_patterns = options.include_patterns or []
    exclude_patterns = options.exclude_patterns or []
    top_level_state = _top_level_state_names(tree)
    overloaded_names = {
        stmt.name
        for stmt in tree.body
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)) and _is_overload_function(stmt)
    }
    eager_references = _collect_eager_top_level_references(tree)

    for stmt in tree.body:
        if not isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if max_lineno is not None and statement_start_lineno(stmt) >= max_lineno:
            continue
        if options.public_only and stmt.name.startswith("_"):
            continue
        if include_patterns and not any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in include_patterns):
            continue
        if exclude_patterns and any(fnmatch.fnmatchcase(stmt.name, pattern) for pattern in exclude_patterns):
            continue
        if stmt.end_lineno is None:
            raise PySplitError(f"Could not determine end line for function '{stmt.name}'.")

        skip_reason = ""
        if stmt.decorator_list:
            skip_reason = "decorated functions are left unchanged"
        elif stmt.name in overloaded_names:
            skip_reason = "overloaded functions are left unchanged"
        elif stmt.name in eager_references:
            skip_reason = "functions referenced during module initialization are left unchanged"
        elif _uses_dynamic_code_execution(stmt):
            skip_reason = "functions using dynamic code execution are left unchanged"
        elif _global_statement_names(stmt):
            skip_reason = "functions with global statements are left unchanged"
        elif _contains_nested_definition(stmt):
            skip_reason = "functions with nested definitions are left unchanged"
        elif _signature_references_state(stmt, top_level_state):
            skip_reason = "functions with module-state defaults are left unchanged"

        candidates.append(
            _SemanticFunction(
                node=stmt,
                start_lineno=statement_start_lineno(stmt),
                end_lineno=stmt.end_lineno,
                skip_reason=skip_reason,
            )
        )

    return candidates


def _infer_record_groups(candidates: list[_SemanticFunction], explicit_class_name: str | None) -> list[_RecordGroup]:
    by_prefix: dict[str, list[_SemanticFunction]] = {}
    factories: dict[str, _SemanticFunction] = {}
    for candidate in candidates:
        node = candidate.node
        if isinstance(node, ast.AsyncFunctionDef):
            continue
        if node.name.startswith("create_"):
            prefix = node.name.removeprefix("create_")
            if prefix and _returned_dict_fields(node):
                factories[prefix] = candidate
            continue
        prefix, method_name = _record_method_parts(node)
        if prefix and method_name:
            by_prefix.setdefault(prefix, []).append(candidate)

    groups: list[_RecordGroup] = []
    for prefix, methods in sorted(by_prefix.items()):
        fields = _record_fields(methods)
        factory = factories.get(prefix)
        field_defaults = _returned_dict_fields(factory.node) if factory is not None else {}
        all_fields = sorted(fields | set(field_defaults))
        if len(methods) < 2 and factory is None:
            continue
        if not all_fields:
            continue
        class_name = explicit_class_name if explicit_class_name and len(by_prefix) == 1 else _pascal_name(prefix)
        entity_base_name = f"{class_name}Entity" if "id" in all_fields else ""
        groups.append(
            _RecordGroup(
                prefix=prefix,
                class_name=class_name,
                entity_base_name=entity_base_name,
                instance_arg=prefix,
                methods=methods,
                factory=factory,
                fields=all_fields,
                field_defaults=field_defaults,
            )
        )
    return groups


def _record_method_parts(node: ast.FunctionDef | ast.AsyncFunctionDef) -> tuple[str, str]:
    if "_" not in node.name or not node.args.args:
        return "", ""
    prefix, method_name = node.name.split("_", 1)
    if node.args.args[0].arg != prefix:
        return "", ""
    return prefix, method_name


def _record_fields(candidates: list[_SemanticFunction]) -> set[str]:
    fields: set[str] = set()
    for candidate in candidates:
        instance_arg = candidate.node.args.args[0].arg
        for node in ast.walk(candidate.node):
            field_name = _string_subscript_field(node, instance_arg)
            if field_name:
                fields.add(field_name)
    return fields


def _returned_dict_fields(node: ast.FunctionDef | ast.AsyncFunctionDef) -> dict[str, ast.expr]:
    for statement in node.body:
        if not isinstance(statement, ast.Return) or not isinstance(statement.value, ast.Dict):
            continue
        fields: dict[str, ast.expr] = {}
        for key, value in zip(statement.value.keys, statement.value.values, strict=False):
            if isinstance(key, ast.Constant) and isinstance(key.value, str):
                fields[key.value] = value
        return fields
    return {}


def _rewrite_record_oop_source(source_text: str, tree: ast.Module, groups: list[_RecordGroup]) -> str:
    candidates = sorted(
        [candidate for group in groups for candidate in _record_group_candidates(group)],
        key=lambda candidate: candidate.start_lineno,
    )
    replacements = {
        candidate.node.name: _build_record_wrapper(candidate.node, group)
        for group in groups
        for candidate in _record_group_candidates(group)
    }
    lines = source_text.splitlines(keepends=True)
    class_block = "\n".join(_build_record_class_block(group).rstrip() for group in groups) + "\n\n"
    insertion_lineno = _generated_class_insertion_lineno(tree, len(lines))

    output: list[str] = []
    cursor = 1
    inserted_class = False
    for candidate in candidates:
        if not inserted_class and cursor <= insertion_lineno <= candidate.start_lineno:
            output.extend(lines[cursor - 1 : insertion_lineno - 1])
            output.append(class_block)
            cursor = insertion_lineno
            inserted_class = True
        output.extend(lines[cursor - 1 : candidate.start_lineno - 1])
        output.append(replacements[candidate.node.name])
        cursor = candidate.end_lineno + 1
    if not inserted_class:
        output.extend(lines[cursor - 1 : insertion_lineno - 1])
        output.append(class_block)
        cursor = insertion_lineno
    output.extend(lines[cursor - 1 :])

    return _normalize_rewritten_source("".join(output))


def _record_group_candidates(group: _RecordGroup) -> list[_SemanticFunction]:
    return [*([group.factory] if group.factory is not None else []), *group.methods]


def _build_record_class_block(group: _RecordGroup) -> str:
    parts = ["from dataclasses import dataclass, field", "", SEMANTIC_OOP_MARKER]
    if group.entity_base_name:
        parts.extend(
            [
                "@dataclass(slots=True)",
                f"class {group.entity_base_name}:",
                "    id: object | None = None",
                "",
            ]
        )
    base_suffix = f"({group.entity_base_name})" if group.entity_base_name else ""
    parts.extend(["@dataclass(slots=True)", f"class {group.class_name}{base_suffix}:"])
    for field_name in group.fields:
        if group.entity_base_name and field_name == "id":
            continue
        parts.append(f"    {_attribute_name(field_name)}: object = {_field_default_source(group, field_name)}")
    parts.append("")
    parts.append("    @classmethod")
    parts.append("    def from_mapping(cls, data):")
    parts.append(f"        values = {{{', '.join(repr(field) for field in group.fields)}}}")
    parts.append("        return cls(**{field_name: data[field_name] for field_name in values if field_name in data})")
    parts.append("")
    parts.append("    def to_mapping(self):")
    mapping_items = ", ".join(f"{field!r}: self.{_attribute_name(field)}" for field in group.fields)
    parts.append(f"        return {{{mapping_items}}}")
    parts.append("")
    for candidate in group.methods:
        method_source = _build_record_method_source(candidate.node, group)
        parts.extend("    " + line if line else "" for line in method_source.splitlines())
        parts.append("")
    parts.append("")
    parts.append(f"def {_record_adapter_name(group.prefix)}(value):")
    parts.append(
        f"    return value if isinstance(value, {group.class_name}) "
        f"else {group.class_name}.from_mapping(value)"
    )
    return "\n".join(parts).rstrip() + "\n"


def _field_default_source(group: _RecordGroup, field_name: str) -> str:
    default = group.field_defaults.get(field_name)
    if isinstance(default, ast.List) and not default.elts:
        return "field(default_factory=list)"
    if isinstance(default, ast.Dict) and not default.keys:
        return "field(default_factory=dict)"
    if isinstance(default, ast.Set) and not default.elts:
        return "field(default_factory=set)"
    if default is not None:
        return ast.unparse(default)
    return "None"


def _build_record_method_source(node: ast.FunctionDef | ast.AsyncFunctionDef, group: _RecordGroup) -> str:
    method_node = copy.deepcopy(node)
    method_node.name = method_node.name.removeprefix(f"{group.prefix}_")
    method_node.decorator_list = []
    method_node.args.args = [ast.arg(arg="self"), *method_node.args.args[1:]]
    method_names = {
        candidate.node.name: candidate.node.name.removeprefix(f"{group.prefix}_") for candidate in group.methods
    }
    transformer = _RecordMethodTransformer(
        instance_arg=group.instance_arg,
        fields=set(group.fields),
        method_names=method_names,
    )
    method_node = transformer.visit(method_node)
    ast.fix_missing_locations(method_node)
    return ast.unparse(method_node)


def _build_record_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef, group: _RecordGroup) -> str:
    if group.factory is not None and node.name == group.factory.node.name:
        signature = ast.unparse(node.args)
        return f"def {node.name}({signature}):\n    return {_record_factory_call(group.factory.node, group)}\n\n"
    signature = ast.unparse(node.args)
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    instance_arg = node.args.args[0].arg
    method_name = node.name.removeprefix(f"{group.prefix}_")
    call_args = _call_arguments_without_first(node.args)
    call_suffix = f"({call_args})" if call_args else "()"
    return (
        f"def {node.name}({signature}){returns}:\n"
        f"    return {_record_adapter_name(group.prefix)}({instance_arg}).{method_name}{call_suffix}\n\n"
    )


def _record_factory_call(node: ast.FunctionDef | ast.AsyncFunctionDef, group: _RecordGroup) -> str:
    fields = _returned_dict_fields(node)
    args = ", ".join(f"{_attribute_name(field)}={ast.unparse(value)}" for field, value in fields.items())
    return f"{group.class_name}({args})"


def _record_adapter_name(prefix: str) -> str:
    return f"_as_{prefix}"


class _RecordMethodTransformer(ast.NodeTransformer):
    def __init__(self, *, instance_arg: str, fields: set[str], method_names: dict[str, str]) -> None:
        self._instance_arg = instance_arg
        self._fields = fields
        self._method_names = method_names

    def visit_Call(self, node: ast.Call) -> ast.AST:
        visited = self.generic_visit(node)
        if (
            isinstance(visited, ast.Call)
            and isinstance(visited.func, ast.Name)
            and visited.func.id in self._method_names
            and visited.args
            and isinstance(visited.args[0], ast.Name)
            and visited.args[0].id == self._instance_arg
        ):
            visited.func = ast.Attribute(
                value=ast.Name(id="self", ctx=ast.Load()),
                attr=self._method_names[visited.func.id],
                ctx=ast.Load(),
            )
            visited.args = visited.args[1:]
        return visited

    def visit_Subscript(self, node: ast.Subscript) -> ast.AST:
        visited = self.generic_visit(node)
        field_name = _string_subscript_field(visited, self._instance_arg)
        if isinstance(visited, ast.Subscript) and field_name and field_name in self._fields:
            return ast.copy_location(
                ast.Attribute(
                    value=ast.Name(id="self", ctx=ast.Load()),
                    attr=_attribute_name(field_name),
                    ctx=visited.ctx,
                ),
                visited,
            )
        return visited


def _string_subscript_field(node: ast.AST, instance_arg: str) -> str:
    if (
        isinstance(node, ast.Subscript)
        and isinstance(node.value, ast.Name)
        and node.value.id == instance_arg
        and isinstance(node.slice, ast.Constant)
        and isinstance(node.slice.value, str)
    ):
        return node.slice.value
    return ""


def _rewrite_semantic_oop_source(
    source_text: str,
    tree: ast.Module,
    candidates: list[_SemanticFunction],
    *,
    class_name: str,
    instance_name: str,
    method_names: set[str],
    state_names: list[str],
) -> str:
    candidates = sorted(candidates, key=lambda candidate: candidate.start_lineno)
    lines = source_text.splitlines(keepends=True)
    class_block = _build_semantic_class_block(candidates, class_name, instance_name, method_names, state_names)
    insertion_lineno = _generated_class_insertion_lineno(tree, len(lines))

    output: list[str] = []
    cursor = 1
    inserted_class = False
    for candidate in candidates:
        if not inserted_class and cursor <= insertion_lineno <= candidate.start_lineno:
            output.extend(lines[cursor - 1 : insertion_lineno - 1])
            output.append(class_block)
            cursor = insertion_lineno
            inserted_class = True
        output.extend(lines[cursor - 1 : candidate.start_lineno - 1])
        output.append(_build_instance_wrapper(candidate.node, instance_name))
        cursor = candidate.end_lineno + 1
    if not inserted_class:
        output.extend(lines[cursor - 1 : insertion_lineno - 1])
        output.append(class_block)
        cursor = insertion_lineno
    output.extend(lines[cursor - 1 :])

    return _normalize_rewritten_source("".join(output))


def _build_semantic_class_block(
    candidates: list[_SemanticFunction],
    class_name: str,
    instance_name: str,
    method_names: set[str],
    state_names: list[str],
) -> str:
    class_parts = [SEMANTIC_OOP_MARKER, f"class {class_name}:"]
    if state_names:
        parameters = ", ".join(f"{_attribute_name(name)}={name}" for name in state_names)
        class_parts.append(f"    def __init__(self, {parameters}):")
        for state_name in state_names:
            attribute_name = _attribute_name(state_name)
            class_parts.append(f"        self.{attribute_name} = {attribute_name}")
        class_parts.append("")

    for candidate in candidates:
        method_source = _build_instance_method_source(candidate.node, method_names, set(state_names))
        class_parts.extend("    " + line if line else "" for line in method_source.splitlines())
        class_parts.append("")

    if not candidates and not state_names:
        class_parts.append("    pass")
    class_parts.append("")
    class_parts.append(f"{instance_name} = {class_name}()")
    return "\n".join(class_parts).rstrip() + "\n\n"


def _build_instance_method_source(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    method_names: set[str],
    state_names: set[str],
) -> str:
    method_node = copy.deepcopy(node)
    method_node.decorator_list = []
    method_node.args.args.insert(0, ast.arg(arg="self"))
    local_names = _function_local_names(method_node)
    transformer = _InstanceMethodTransformer(
        method_names=method_names,
        state_names=state_names,
        local_names=local_names,
    )
    method_node = transformer.visit(method_node)
    ast.fix_missing_locations(method_node)
    return ast.unparse(method_node)


def _build_instance_wrapper(node: ast.FunctionDef | ast.AsyncFunctionDef, instance_name: str) -> str:
    async_prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    await_prefix = "await " if isinstance(node, ast.AsyncFunctionDef) else ""
    returns = f" -> {ast.unparse(node.returns)}" if node.returns is not None else ""
    signature = ast.unparse(node.args)
    call_args = _call_arguments(node.args)
    call = f"{await_prefix}{instance_name}.{node.name}({call_args})"
    return f"{async_prefix}def {node.name}({signature}){returns}:\n    return {call}\n\n"


class _InstanceMethodTransformer(ast.NodeTransformer):
    def __init__(self, *, method_names: set[str], state_names: set[str], local_names: set[str]) -> None:
        self._method_names = method_names
        self._state_names = state_names
        self._local_names = local_names
        self._state_attributes = {name: _attribute_name(name) for name in state_names}

    def visit_Call(self, node: ast.Call) -> ast.AST:
        visited = self.generic_visit(node)
        if (
            isinstance(visited, ast.Call)
            and isinstance(visited.func, ast.Name)
            and visited.func.id in self._method_names
        ):
            visited.func = ast.Attribute(
                value=ast.Name(id="self", ctx=ast.Load()),
                attr=visited.func.id,
                ctx=ast.Load(),
            )
        return visited

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if (
            isinstance(node.ctx, ast.Load)
            and node.id in self._state_names
            and node.id not in self._local_names
        ):
            return ast.copy_location(
                ast.Attribute(
                    value=ast.Name(id="self", ctx=ast.Load()),
                    attr=self._state_attributes[node.id],
                    ctx=node.ctx,
                ),
                node,
            )
        return node


def _infer_instance_state(candidates: list[_SemanticFunction], top_level_state: set[str]) -> list[str]:
    used_state: set[str] = set()
    for candidate in candidates:
        local_names = _function_local_names(candidate.node)
        for node in ast.walk(candidate.node):
            if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Load):
                if node.id in top_level_state and node.id not in local_names:
                    used_state.add(node.id)
    return sorted(used_state)


def _select_service_candidates(
    candidates: list[_SemanticFunction],
    top_level_state: set[str],
    *,
    file_path: Path,
    explicit_class_name: bool,
) -> tuple[list[_SemanticFunction], dict[str, str]]:
    if explicit_class_name:
        return candidates, {}

    if _is_low_signal_oop_module(file_path):
        return (
            [],
            {
                candidate.node.name: "entrypoint and test modules are left procedural unless --class-name is explicit"
                for candidate in candidates
            },
        )

    stateful_names = {
        candidate.node.name
        for candidate in candidates
        if _function_uses_top_level_state(candidate.node, top_level_state)
    }
    if not stateful_names:
        return (
            [],
            {
                candidate.node.name: "no cohesive instance state or domain object ownership could be inferred"
                for candidate in candidates
            },
        )

    candidate_names = {candidate.node.name for candidate in candidates}
    call_graph = {
        candidate.node.name: _called_candidate_names(candidate.node, candidate_names)
        for candidate in candidates
    }
    selected_names = set(stateful_names)
    changed = True
    while changed:
        changed = False
        for name, called_names in call_graph.items():
            if name in selected_names:
                missing_callees = called_names - selected_names
                if missing_callees:
                    selected_names.update(missing_callees)
                    changed = True
            elif called_names & selected_names:
                selected_names.add(name)
                changed = True

    selected = [candidate for candidate in candidates if candidate.node.name in selected_names]
    skipped = {
        candidate.node.name: "function is not part of the inferred stateful service boundary"
        for candidate in candidates
        if candidate.node.name not in selected_names
    }
    return selected, skipped


def _function_uses_top_level_state(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    top_level_state: set[str],
) -> bool:
    local_names = _function_local_names(node)
    return any(
        isinstance(child, ast.Name)
        and isinstance(child.ctx, ast.Load)
        and child.id in top_level_state
        and child.id not in local_names
        for child in ast.walk(node)
    )


def _called_candidate_names(
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    candidate_names: set[str],
) -> set[str]:
    return {
        child.func.id
        for child in ast.walk(node)
        if isinstance(child, ast.Call)
        and isinstance(child.func, ast.Name)
        and child.func.id in candidate_names
    }


def _is_low_signal_oop_module(file_path: Path) -> bool:
    stem = file_path.stem
    return stem == "main" or stem.startswith("test_") or stem.endswith("_test")


def _top_level_state_names(tree: ast.Module) -> set[str]:
    names: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
        elif isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            names.add(stmt.target.id)
    return names


def _function_local_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names = {arg.arg for arg in [*node.args.posonlyargs, *node.args.args, *node.args.kwonlyargs]}
    if node.args.vararg is not None:
        names.add(node.args.vararg.arg)
    if node.args.kwarg is not None:
        names.add(node.args.kwarg.arg)
    for child in ast.walk(node):
        if isinstance(child, ast.Name) and isinstance(child.ctx, (ast.Store, ast.Del)):
            names.add(child.id)
        elif isinstance(child, (ast.For, ast.AsyncFor)):
            names.update(_stored_names(child.target))
        elif isinstance(child, ast.With):
            for item in child.items:
                if item.optional_vars is not None:
                    names.update(_stored_names(item.optional_vars))
        elif isinstance(child, ast.ExceptHandler) and child.name is not None:
            names.add(child.name)
    names.discard("self")
    return names


def _stored_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name)}


def _global_statement_names(node: ast.FunctionDef | ast.AsyncFunctionDef) -> set[str]:
    names: set[str] = set()
    for child in ast.walk(node):
        if isinstance(child, ast.Global):
            names.update(child.names)
    return names


def _contains_nested_definition(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    for child in ast.iter_child_nodes(node):
        for nested in ast.walk(child):
            if isinstance(nested, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)):
                return True
    return False


def _signature_references_state(node: ast.FunctionDef | ast.AsyncFunctionDef, state_names: set[str]) -> bool:
    signature_nodes: list[ast.AST] = [
        *node.args.defaults,
        *(default for default in node.args.kw_defaults if default is not None),
    ]
    signature_nodes.extend(arg.annotation for arg in _all_arguments(node.args) if arg.annotation is not None)
    if node.returns is not None:
        signature_nodes.append(node.returns)
    return any(name in state_names for signature_node in signature_nodes for name in _loaded_names(signature_node))


def _all_arguments(args: ast.arguments) -> list[ast.arg]:
    return [*args.posonlyargs, *args.args, *args.kwonlyargs]


def _first_generated_marker_lineno(source_text: str) -> int | None:
    marker_lines: list[int] = []
    for marker in (
        SEMANTIC_OOP_MARKER,
        "# Auto-generated by ManaSplice: functional facade",
        "# Auto-generated by ManaSplice: event facade",
        "# Auto-generated by ManaSplice: OOP class",
        "# Auto-generated by ManaSplice: procedural compatibility class",
    ):
        index = source_text.find(marker)
        if index >= 0:
            marker_lines.append(source_text.count("\n", 0, index) + 1)
    return min(marker_lines) if marker_lines else None


def _collect_eager_top_level_references(tree: ast.Module) -> set[str]:
    references: set[str] = set()
    for stmt in tree.body:
        if isinstance(stmt, (ast.Import, ast.ImportFrom, ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if _is_main_guard(stmt):
            continue
        references.update(_loaded_names(stmt))
    return references


def _loaded_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Load)}


def _uses_dynamic_code_execution(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    dynamic_builtins = {"compile", "eval", "exec"}
    return any(
        isinstance(child, ast.Call) and isinstance(child.func, ast.Name) and child.func.id in dynamic_builtins
        for child in ast.walk(node)
    )


def _generated_class_insertion_lineno(tree: ast.Module, line_count: int) -> int:
    for stmt in tree.body:
        if _is_main_guard(stmt):
            return statement_start_lineno(stmt)
    return line_count + 1


def _is_main_guard(stmt: ast.stmt) -> bool:
    if not isinstance(stmt, ast.If):
        return False
    test = stmt.test
    if not isinstance(test, ast.Compare) or len(test.ops) != 1 or len(test.comparators) != 1:
        return False
    if not isinstance(test.ops[0], ast.Eq):
        return False
    left = test.left
    right = test.comparators[0]
    return (
        isinstance(left, ast.Name)
        and left.id == "__name__"
        and isinstance(right, ast.Constant)
        and right.value == "__main__"
    )


def _call_arguments(args: ast.arguments) -> str:
    names: list[str] = []
    names.extend(arg.arg for arg in args.posonlyargs)
    names.extend(arg.arg for arg in args.args)
    if args.vararg is not None:
        names.append(f"*{args.vararg.arg}")
    names.extend(f"{arg.arg}={arg.arg}" for arg in args.kwonlyargs)
    if args.kwarg is not None:
        names.append(f"**{args.kwarg.arg}")
    return ", ".join(names)


def _call_arguments_without_first(args: ast.arguments) -> str:
    call_arguments = _call_arguments(args)
    names = call_arguments.split(", ") if call_arguments else []
    return ", ".join(names[1:])


def _default_class_name(file_path: Path) -> str:
    stem = file_path.stem
    if stem == "__init__":
        stem = file_path.parent.name
    base = _pascal_name(stem)
    return f"{base}Service"


def _pascal_name(value: str) -> str:
    words = [word for word in value.replace("-", "_").split("_") if word]
    return "".join(word[:1].upper() + word[1:] for word in words) or "Module"


def _default_instance_name(class_name: str) -> str:
    words: list[str] = []
    current = ""
    for character in class_name:
        if character.isupper() and current:
            words.append(current)
            current = character
        else:
            current += character
    if current:
        words.append(current)
    return "_DEFAULT_" + "_".join(word.upper() for word in words)


def _attribute_name(name: str) -> str:
    return name.lower()


def _has_top_level_name(tree: ast.Module, name: str) -> bool:
    for stmt in tree.body:
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) and stmt.name == name:
            return True
        if isinstance(stmt, ast.Assign) and name in _assigned_names(stmt):
            return True
        if isinstance(stmt, ast.AnnAssign) and name in _assigned_names(stmt):
            return True
    return False


def _assigned_names(node: ast.AST) -> set[str]:
    return {child.id for child in ast.walk(node) if isinstance(child, ast.Name) and isinstance(child.ctx, ast.Store)}


def _is_overload_function(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(_decorator_name(decorator) == "overload" for decorator in node.decorator_list)


def _decorator_name(node: ast.expr) -> str:
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        return node.attr
    if isinstance(node, ast.Call):
        return _decorator_name(node.func)
    return ""


def _normalize_rewritten_source(source_text: str) -> str:
    updated = source_text
    while "\n\n\n" in updated:
        updated = updated.replace("\n\n\n", "\n\n")
    return updated.lstrip("\n")


def _build_preview_diffs(file_changes: list[FileChange]) -> list[str]:
    diffs: list[str] = []
    for change in file_changes:
        diff_lines = list(
            difflib.unified_diff(
                change.before_text.splitlines(),
                change.after_text.splitlines(),
                fromfile=str(change.path),
                tofile=str(change.path),
                lineterm="",
            )
        )
        if diff_lines:
            diffs.append("\n".join(diff_lines))
    return diffs
